### ISSUE TITLE
using RabbitMQ 

### ISSUE THREAD

**Issue by bnouhanna** [coatyio/coaty-js#11]
**Describe the bug**
I am using a RabbitMQ broker with the MQTT plugin as communication for coaty, and it is causing issues in the communication between agents. 

- Specifying the namespace, gives the following error:

![image](https://user-images.githubusercontent.com/15689673/96888260-b5e7b800-1485-11eb-9c86-ad2b72b8a409.png)

- Not specifying the namespace doesn't allow the discovery of other containers and gives this error:

![image](https://user-images.githubusercontent.com/15689673/96888694-2ee70f80-1486-11eb-8edc-bc28046d9981.png)

- Enabling the shouldEnableCrossNamespacing gives this error: 

![image](https://user-images.githubusercontent.com/15689673/96889195-a9179400-1486-11eb-9ffe-78a6121b567a.png)

**Is this a regression?**
I don't know if the previous versions had the same issue 

**To Reproduce**
Minimal steps to reproduce the behavior:
1. Use RabbitMQ broker
2. use two coaty agents: The first publishes data once it starts. The second is subscribed to the data and is also able to discover agent 1 type
3. Communication between the two agents is not possible as well as the discovery

**Expected behavior**
I expect that the two agents can communicate exactly the same way as when using Mosquitto broker for example. 

**Your Environment (please complete the following information):**
- Coaty Version: 1.5.2
- OS:  Windows 10

**Comment by ffa500** [comment]
### Limitations of RabbitMQ  MQTT

The RabbitMQ MQTT plugin targets MQTT 3.1.1 but it has *one* important limitation, as mentioned [in the documentation](https://www.rabbitmq.com/mqtt.html#implementation):

> Note that MQTT uses slashes ("/") for topic segment separators and AMQP 0-9-1
> uses dots. This plugin translates patterns under the hood to bridge the two,
> for example, `cities/london` becomes `cities.london` and vice versa. **This
> has one important limitation**: MQTT topics that have dots in them won't work
> as expected and are to be avoided, the same goes for AMQP 0-9-1 routing keys
> that contains slashes.

Note: The MQTT plugin also has other [limitations](https://www.rabbitmq.com/mqtt.html#limitations) but these do not affect Coaty directly.

### Findings

In your first example, you are specifying a namespace with a dot (i.e. `coaty.demonstartor2`) which translates to two topic segments `coaty/demonstartor2`. You could fix this by choosing a namespace without dots like `coaty:demonstartor2`.

But even this won't help as Coaty core object types have names that include dots. In your examples, an Advertise event on a SensorThings `Thing` object is published. The plugin transforms the corresponding object type `"coaty.SensorThings.Thing"` into *three* separate topic segments `coaty/SensorThings/Thing` resulting in `ADV::coaty/SensorThings/Thing` instead of `ADV::coaty.SensorThings.Thing`. This topic structure no longer conforms with the structure of Coaty topics, thus - upon receipt of such messages - an "Invalid topic" error is reported and the message is dropped, i.e. not dispatched to the Coaty application.

As you mention, Discover-Resolve events work perfectly because these events don't specify object types on the event topic segment.

**To summarize**: The RabbitMQ MQTT plugin is not compatible with Coaty applications that use the Coaty MQTT communication binding, as the plugin is not implementing the MQTT protocol 100% correctly.

### Solutions

**Quick and easy way**: Do not use RabbitMQ as an MQTT broker for Coaty applications. Instead, use a full-fledged MQTT broker like mosquitto, HiveMQ, VerneMQ, EMQ X, or the Coaty broker (for development testing).

**More elaborate way**: In Coaty 3, the next major version of Coaty, we plan to restrict the characters which are valid in Coaty topic segments to a very limited set such as `A-Z`, `a-z`, `.` and `-`. We could then provide a compatibility flag for AMQP-based brokers as part of the Coaty MQTT binding. Whenever this flag is enabled, the binding specially encodes any dot characters inside Coaty topic segments by substituting them with a dedicated replacement character before publishing. In inbound messages, the replacement characters are reverted back into dots. We are using a similar approach in the Coaty WAMP binding which - like AMQP - uses dots as topic segment separators. Unfortunately, we cannot use this technique in Coaty 2 as any characters are allowed which comply with the MQTT specification. Thus, there is no dedicated replacement character.

**Comment by bnouhanna** [comment]
Thank you for your prompt response. 
This issue arises because I need to publish and observe raw messages from an external broker in the cloud (RabitMQ). I have therefore two questions/ suggestions:
 
- Is it possible to have coaty container with two communicationManager one using an MQTT broker (Mosquitto for example) for communication between coaty agents and for raw messages use the RabitMQ broker?

- Would it be possible to assign a broker connection to the raw messages for example this.communicationManager.observeRaw(brokerInfo, "topicName")?

Any ideas or suggestions?

**Comment by ffa500** [comment]
By design, one Coaty container always hosts exactly one communication manager (which connects to one broker). Assigning a different brokerUrl to observeRaw is not a good idea as it would break this conceptual design.

There is a much cleaner solution to your problem regarding observation of raw external messages:

* Define two separate Coaty containers/agents running inside your Node.js application (in the same process!).
* In one container, configure the RabbitMQ broker URl in communication options and implement a controller that solely observes the raw external events.
* On the other container, configure the MQTT broker of your distributed application, for Coaty event communication.
* Transfer any raw external messages received by the controller in the first container to a controller in the second container for further processing.

To communicate raw data between the two controllers, I suggest to use RxJs Observables. The controller in the Rabbit container exposes the external payload on an Observable Subject, e.g. via a public  getter method. The controller that needs to process this information in the other container just subscribes to this subject and handles incoming values.

Code should look like this:

```ts
// Startup two agent containers.
const containerRaw = Container.resolve(componentsRaw, configRaw);
const container = Container.resolve(components, config);

// Interconnect the two containers/controllers.
const rawController = containerRaw.getController<RawController>("RawController");
const processingController = container.getController<ProcessingController>("ProcessingController");
processingController.registerRaw(rawController.rawObservable);
```

The `RawController` code looks like this:

```ts
import { Subject } from "rxjs";

export class RawController extends Controller {
    private _rawSubject = new Subject();

    onCommunicationManagerStarting() {
        this.communicationManager.observeRaw("my-external-topic-without-dots-to-observe")
              .subscribe(topicWithPayload => this._rawSubject.next(topicWithPayload));
    }

    get rawObservable() {
        return this.rawSubject.asObservable();
    }
}
```

The `ProcessingController` code looks like this:

```ts
import { Observable } from "rxjs";

export class ProcessingController extends Controller {

    registerRaw(rawObs: Observable) {
        rawObs.subscribe(([topic, payload]) => {
            // handle raw topic with payload here...
        });
    }
}
```

**Comment by bnouhanna** [comment]
Yes, it is working. Thank you very much for your support.
